export enum TransactionType {
    DEBIT = "DEBIT",
    CREDIT = "CREDIT",
}

export enum TransactionPurpose {
    BOOKING_PAYMENT = "BOOKING_PAYMENT",
    BOOKING_REFUND = "BOOKING_REFUND",
    TICKET_PURCHASE = "TICKET_PURCHASE",
    TICKET_REFUND = "TICKET_REFUND",
    TOPUP = "TOPUP",
    ADJUSTMENT = "ADJUSTMENT",
    MEMBERSHIP_PAYMENT = "MEMBERSHIP_PAYMENT",
    MEMBERSHIP_UPGRADE = "MEMBERSHIP_UPGRADE",
}